# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('vendor', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=20)),
                ('batch_num', models.CharField(max_length=10)),
                ('batch_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], max_length=10)),
            ],
        ),
    ]
